fragment BooksParts on Books {
  __typename
  title
  author
  description
  format
  price
  coverImageUrl
  category
  publishedYear
  pages
  isbn
  body
}

fragment PagesParts on Pages {
  __typename
  title
  description
  body
}
