fragment BooksParts on Books {
  __typename
  title
  author
  description
  format
  price
  coverImageUrl
  category
  publishedYear
  pages
  isbn
  body
}

fragment PagesParts on Pages {
  __typename
  title
  description
  hero {
    __typename
    logoUrl
    logoAlt
    primaryButton {
      __typename
      text
      url
    }
    secondaryButton {
      __typename
      text
      url
    }
  }
  featuredBooks {
    __typename
    title
    description
    viewAllButton {
      __typename
      text
      url
    }
  }
  about {
    __typename
    imageUrl
    imageAlt
    learnMoreButton {
      __typename
      text
      url
    }
  }
  testimonials {
    __typename
    title
    description
    items {
      __typename
      quote
      author
      rating
    }
  }
  quickFacts {
    __typename
    title
    countriesVisited
    yearsAsNomad
    booksPublished
    legalCasesWon
  }
  body
}

fragment FooterParts on Footer {
  __typename
  title
  companyName
  description
  copyrightYear
  copyrightText
  socialMedia {
    __typename
    twitter
    facebook
    linkedin
  }
  facebookGroup {
    __typename
    title
    description
    url
    buttonText
  }
}
