//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  books: Books;
  booksConnection: BooksConnection;
  pages: Pages;
  pagesConnection: PagesConnection;
  footer: Footer;
  footerConnection: FooterConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBooksArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBooksConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BooksFilter>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};


export type QueryFooterArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFooterConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FooterFilter>;
};

export type DocumentFilter = {
  books?: InputMaybe<BooksFilter>;
  pages?: InputMaybe<PagesFilter>;
  footer?: InputMaybe<FooterFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Books | Pages | Footer | Folder;

export type Books = Node & Document & {
  __typename?: 'Books';
  title: Scalars['String']['output'];
  author: Scalars['String']['output'];
  description: Scalars['JSON']['output'];
  format: Scalars['String']['output'];
  price: Scalars['Float']['output'];
  coverImageUrl: Scalars['String']['output'];
  category: Scalars['String']['output'];
  publishedYear: Scalars['Float']['output'];
  pages: Scalars['Float']['output'];
  isbn?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooksFilter = {
  title?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
  format?: InputMaybe<StringFilter>;
  price?: InputMaybe<NumberFilter>;
  coverImageUrl?: InputMaybe<ImageFilter>;
  category?: InputMaybe<StringFilter>;
  publishedYear?: InputMaybe<NumberFilter>;
  pages?: InputMaybe<NumberFilter>;
  isbn?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BooksConnectionEdges = {
  __typename?: 'BooksConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Books>;
};

export type BooksConnection = Connection & {
  __typename?: 'BooksConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BooksConnectionEdges>>>;
};

export type PagesHeroPrimaryButton = {
  __typename?: 'PagesHeroPrimaryButton';
  text: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type PagesHeroSecondaryButton = {
  __typename?: 'PagesHeroSecondaryButton';
  text: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type PagesHero = {
  __typename?: 'PagesHero';
  logoUrl?: Maybe<Scalars['String']['output']>;
  logoAlt?: Maybe<Scalars['String']['output']>;
  primaryButton?: Maybe<PagesHeroPrimaryButton>;
  secondaryButton?: Maybe<PagesHeroSecondaryButton>;
};

export type PagesFeaturedBooksViewAllButton = {
  __typename?: 'PagesFeaturedBooksViewAllButton';
  text: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type PagesFeaturedBooks = {
  __typename?: 'PagesFeaturedBooks';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  viewAllButton?: Maybe<PagesFeaturedBooksViewAllButton>;
};

export type PagesAboutLearnMoreButton = {
  __typename?: 'PagesAboutLearnMoreButton';
  text: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type PagesAbout = {
  __typename?: 'PagesAbout';
  imageUrl?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  learnMoreButton?: Maybe<PagesAboutLearnMoreButton>;
};

export type PagesTestimonialsItems = {
  __typename?: 'PagesTestimonialsItems';
  quote: Scalars['String']['output'];
  author: Scalars['String']['output'];
  rating: Scalars['Float']['output'];
};

export type PagesTestimonials = {
  __typename?: 'PagesTestimonials';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  items?: Maybe<Array<Maybe<PagesTestimonialsItems>>>;
};

export type Pages = Node & Document & {
  __typename?: 'Pages';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  hero?: Maybe<PagesHero>;
  featuredBooks?: Maybe<PagesFeaturedBooks>;
  about?: Maybe<PagesAbout>;
  testimonials?: Maybe<PagesTestimonials>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesHeroPrimaryButtonFilter = {
  text?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type PagesHeroSecondaryButtonFilter = {
  text?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type PagesHeroFilter = {
  logoUrl?: InputMaybe<StringFilter>;
  logoAlt?: InputMaybe<StringFilter>;
  primaryButton?: InputMaybe<PagesHeroPrimaryButtonFilter>;
  secondaryButton?: InputMaybe<PagesHeroSecondaryButtonFilter>;
};

export type PagesFeaturedBooksViewAllButtonFilter = {
  text?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type PagesFeaturedBooksFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  viewAllButton?: InputMaybe<PagesFeaturedBooksViewAllButtonFilter>;
};

export type PagesAboutLearnMoreButtonFilter = {
  text?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type PagesAboutFilter = {
  imageUrl?: InputMaybe<StringFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  learnMoreButton?: InputMaybe<PagesAboutLearnMoreButtonFilter>;
};

export type PagesTestimonialsItemsFilter = {
  quote?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  rating?: InputMaybe<NumberFilter>;
};

export type PagesTestimonialsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  items?: InputMaybe<PagesTestimonialsItemsFilter>;
};

export type PagesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  hero?: InputMaybe<PagesHeroFilter>;
  featuredBooks?: InputMaybe<PagesFeaturedBooksFilter>;
  about?: InputMaybe<PagesAboutFilter>;
  testimonials?: InputMaybe<PagesTestimonialsFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type FooterSocialMedia = {
  __typename?: 'FooterSocialMedia';
  twitter?: Maybe<Scalars['String']['output']>;
  facebook?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
};

export type FooterFacebookGroup = {
  __typename?: 'FooterFacebookGroup';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  url: Scalars['String']['output'];
  buttonText: Scalars['String']['output'];
};

export type Footer = Node & Document & {
  __typename?: 'Footer';
  title: Scalars['String']['output'];
  companyName: Scalars['String']['output'];
  description: Scalars['String']['output'];
  copyrightYear: Scalars['Float']['output'];
  copyrightText: Scalars['String']['output'];
  socialMedia?: Maybe<FooterSocialMedia>;
  facebookGroup?: Maybe<FooterFacebookGroup>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FooterSocialMediaFilter = {
  twitter?: InputMaybe<StringFilter>;
  facebook?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
};

export type FooterFacebookGroupFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
};

export type FooterFilter = {
  title?: InputMaybe<StringFilter>;
  companyName?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  copyrightYear?: InputMaybe<NumberFilter>;
  copyrightText?: InputMaybe<StringFilter>;
  socialMedia?: InputMaybe<FooterSocialMediaFilter>;
  facebookGroup?: InputMaybe<FooterFacebookGroupFilter>;
};

export type FooterConnectionEdges = {
  __typename?: 'FooterConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Footer>;
};

export type FooterConnection = Connection & {
  __typename?: 'FooterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FooterConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBooks: Books;
  createBooks: Books;
  updatePages: Pages;
  createPages: Pages;
  updateFooter: Footer;
  createFooter: Footer;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBooksArgs = {
  relativePath: Scalars['String']['input'];
  params: BooksMutation;
};


export type MutationCreateBooksArgs = {
  relativePath: Scalars['String']['input'];
  params: BooksMutation;
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationUpdateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};


export type MutationCreateFooterArgs = {
  relativePath: Scalars['String']['input'];
  params: FooterMutation;
};

export type DocumentUpdateMutation = {
  books?: InputMaybe<BooksMutation>;
  pages?: InputMaybe<PagesMutation>;
  footer?: InputMaybe<FooterMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  books?: InputMaybe<BooksMutation>;
  pages?: InputMaybe<PagesMutation>;
  footer?: InputMaybe<FooterMutation>;
};

export type BooksMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  format?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
  coverImageUrl?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  publishedYear?: InputMaybe<Scalars['Float']['input']>;
  pages?: InputMaybe<Scalars['Float']['input']>;
  isbn?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PagesHeroPrimaryButtonMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type PagesHeroSecondaryButtonMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type PagesHeroMutation = {
  logoUrl?: InputMaybe<Scalars['String']['input']>;
  logoAlt?: InputMaybe<Scalars['String']['input']>;
  primaryButton?: InputMaybe<PagesHeroPrimaryButtonMutation>;
  secondaryButton?: InputMaybe<PagesHeroSecondaryButtonMutation>;
};

export type PagesFeaturedBooksViewAllButtonMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type PagesFeaturedBooksMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  viewAllButton?: InputMaybe<PagesFeaturedBooksViewAllButtonMutation>;
};

export type PagesAboutLearnMoreButtonMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type PagesAboutMutation = {
  imageUrl?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  learnMoreButton?: InputMaybe<PagesAboutLearnMoreButtonMutation>;
};

export type PagesTestimonialsItemsMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  rating?: InputMaybe<Scalars['Float']['input']>;
};

export type PagesTestimonialsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<PagesTestimonialsItemsMutation>>>;
};

export type PagesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  hero?: InputMaybe<PagesHeroMutation>;
  featuredBooks?: InputMaybe<PagesFeaturedBooksMutation>;
  about?: InputMaybe<PagesAboutMutation>;
  testimonials?: InputMaybe<PagesTestimonialsMutation>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type FooterSocialMediaMutation = {
  twitter?: InputMaybe<Scalars['String']['input']>;
  facebook?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
};

export type FooterFacebookGroupMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  buttonText?: InputMaybe<Scalars['String']['input']>;
};

export type FooterMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  companyName?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  copyrightYear?: InputMaybe<Scalars['Float']['input']>;
  copyrightText?: InputMaybe<Scalars['String']['input']>;
  socialMedia?: InputMaybe<FooterSocialMediaMutation>;
  facebookGroup?: InputMaybe<FooterFacebookGroupMutation>;
};

export type BooksPartsFragment = { __typename: 'Books', title: string, author: string, description: any, format: string, price: number, coverImageUrl: string, category: string, publishedYear: number, pages: number, isbn?: string | null, body?: any | null };

export type PagesPartsFragment = { __typename: 'Pages', title: string, description: string, body?: any | null, hero?: { __typename: 'PagesHero', logoUrl?: string | null, logoAlt?: string | null, primaryButton?: { __typename: 'PagesHeroPrimaryButton', text: string, url: string } | null, secondaryButton?: { __typename: 'PagesHeroSecondaryButton', text: string, url: string } | null } | null, featuredBooks?: { __typename: 'PagesFeaturedBooks', title: string, description: string, viewAllButton?: { __typename: 'PagesFeaturedBooksViewAllButton', text: string, url: string } | null } | null, about?: { __typename: 'PagesAbout', imageUrl?: string | null, imageAlt?: string | null, learnMoreButton?: { __typename: 'PagesAboutLearnMoreButton', text: string, url: string } | null } | null, testimonials?: { __typename: 'PagesTestimonials', title: string, description: string, items?: Array<{ __typename: 'PagesTestimonialsItems', quote: string, author: string, rating: number } | null> | null } | null };

export type FooterPartsFragment = { __typename: 'Footer', title: string, companyName: string, description: string, copyrightYear: number, copyrightText: string, socialMedia?: { __typename: 'FooterSocialMedia', twitter?: string | null, facebook?: string | null, linkedin?: string | null } | null, facebookGroup?: { __typename: 'FooterFacebookGroup', title: string, description: string, url: string, buttonText: string } | null };

export type BooksQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BooksQuery = { __typename?: 'Query', books: { __typename: 'Books', id: string, title: string, author: string, description: any, format: string, price: number, coverImageUrl: string, category: string, publishedYear: number, pages: number, isbn?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BooksConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BooksFilter>;
}>;


export type BooksConnectionQuery = { __typename?: 'Query', booksConnection: { __typename?: 'BooksConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BooksConnectionEdges', cursor: string, node?: { __typename: 'Books', id: string, title: string, author: string, description: any, format: string, price: number, coverImageUrl: string, category: string, publishedYear: number, pages: number, isbn?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PagesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PagesQuery = { __typename?: 'Query', pages: { __typename: 'Pages', id: string, title: string, description: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'PagesHero', logoUrl?: string | null, logoAlt?: string | null, primaryButton?: { __typename: 'PagesHeroPrimaryButton', text: string, url: string } | null, secondaryButton?: { __typename: 'PagesHeroSecondaryButton', text: string, url: string } | null } | null, featuredBooks?: { __typename: 'PagesFeaturedBooks', title: string, description: string, viewAllButton?: { __typename: 'PagesFeaturedBooksViewAllButton', text: string, url: string } | null } | null, about?: { __typename: 'PagesAbout', imageUrl?: string | null, imageAlt?: string | null, learnMoreButton?: { __typename: 'PagesAboutLearnMoreButton', text: string, url: string } | null } | null, testimonials?: { __typename: 'PagesTestimonials', title: string, description: string, items?: Array<{ __typename: 'PagesTestimonialsItems', quote: string, author: string, rating: number } | null> | null } | null } };

export type PagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
}>;


export type PagesConnectionQuery = { __typename?: 'Query', pagesConnection: { __typename?: 'PagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PagesConnectionEdges', cursor: string, node?: { __typename: 'Pages', id: string, title: string, description: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'PagesHero', logoUrl?: string | null, logoAlt?: string | null, primaryButton?: { __typename: 'PagesHeroPrimaryButton', text: string, url: string } | null, secondaryButton?: { __typename: 'PagesHeroSecondaryButton', text: string, url: string } | null } | null, featuredBooks?: { __typename: 'PagesFeaturedBooks', title: string, description: string, viewAllButton?: { __typename: 'PagesFeaturedBooksViewAllButton', text: string, url: string } | null } | null, about?: { __typename: 'PagesAbout', imageUrl?: string | null, imageAlt?: string | null, learnMoreButton?: { __typename: 'PagesAboutLearnMoreButton', text: string, url: string } | null } | null, testimonials?: { __typename: 'PagesTestimonials', title: string, description: string, items?: Array<{ __typename: 'PagesTestimonialsItems', quote: string, author: string, rating: number } | null> | null } | null } | null } | null> | null } };

export type FooterQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FooterQuery = { __typename?: 'Query', footer: { __typename: 'Footer', id: string, title: string, companyName: string, description: string, copyrightYear: number, copyrightText: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, socialMedia?: { __typename: 'FooterSocialMedia', twitter?: string | null, facebook?: string | null, linkedin?: string | null } | null, facebookGroup?: { __typename: 'FooterFacebookGroup', title: string, description: string, url: string, buttonText: string } | null } };

export type FooterConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FooterFilter>;
}>;


export type FooterConnectionQuery = { __typename?: 'Query', footerConnection: { __typename?: 'FooterConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FooterConnectionEdges', cursor: string, node?: { __typename: 'Footer', id: string, title: string, companyName: string, description: string, copyrightYear: number, copyrightText: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, socialMedia?: { __typename: 'FooterSocialMedia', twitter?: string | null, facebook?: string | null, linkedin?: string | null } | null, facebookGroup?: { __typename: 'FooterFacebookGroup', title: string, description: string, url: string, buttonText: string } | null } | null } | null> | null } };

export const BooksPartsFragmentDoc = gql`
    fragment BooksParts on Books {
  __typename
  title
  author
  description
  format
  price
  coverImageUrl
  category
  publishedYear
  pages
  isbn
  body
}
    `;
export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  title
  description
  hero {
    __typename
    logoUrl
    logoAlt
    primaryButton {
      __typename
      text
      url
    }
    secondaryButton {
      __typename
      text
      url
    }
  }
  featuredBooks {
    __typename
    title
    description
    viewAllButton {
      __typename
      text
      url
    }
  }
  about {
    __typename
    imageUrl
    imageAlt
    learnMoreButton {
      __typename
      text
      url
    }
  }
  testimonials {
    __typename
    title
    description
    items {
      __typename
      quote
      author
      rating
    }
  }
  body
}
    `;
export const FooterPartsFragmentDoc = gql`
    fragment FooterParts on Footer {
  __typename
  title
  companyName
  description
  copyrightYear
  copyrightText
  socialMedia {
    __typename
    twitter
    facebook
    linkedin
  }
  facebookGroup {
    __typename
    title
    description
    url
    buttonText
  }
}
    `;
export const BooksDocument = gql`
    query books($relativePath: String!) {
  books(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BooksParts
  }
}
    ${BooksPartsFragmentDoc}`;
export const BooksConnectionDocument = gql`
    query booksConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BooksFilter) {
  booksConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BooksParts
      }
    }
  }
}
    ${BooksPartsFragmentDoc}`;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export const FooterDocument = gql`
    query footer($relativePath: String!) {
  footer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FooterParts
  }
}
    ${FooterPartsFragmentDoc}`;
export const FooterConnectionDocument = gql`
    query footerConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FooterFilter) {
  footerConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FooterParts
      }
    }
  }
}
    ${FooterPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      books(variables: BooksQueryVariables, options?: C): Promise<{data: BooksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BooksQueryVariables, query: string}> {
        return requester<{data: BooksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BooksQueryVariables, query: string}, BooksQueryVariables>(BooksDocument, variables, options);
      },
    booksConnection(variables?: BooksConnectionQueryVariables, options?: C): Promise<{data: BooksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BooksConnectionQueryVariables, query: string}> {
        return requester<{data: BooksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BooksConnectionQueryVariables, query: string}, BooksConnectionQueryVariables>(BooksConnectionDocument, variables, options);
      },
    pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      },
    footer(variables: FooterQueryVariables, options?: C): Promise<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}> {
        return requester<{data: FooterQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterQueryVariables, query: string}, FooterQueryVariables>(FooterDocument, variables, options);
      },
    footerConnection(variables?: FooterConnectionQueryVariables, options?: C): Promise<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}> {
        return requester<{data: FooterConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FooterConnectionQueryVariables, query: string}, FooterConnectionQueryVariables>(FooterConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  